# Generated by Django 4.1.3 on 2023-07-07 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0023_alter_orderdetails_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extendFromDate', models.DateTimeField(blank=True, null=True)),
                ('extendToDate', models.DateTimeField(blank=True, null=True)),
                ('extendStatus', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=100, null=True)),
                ('extendAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extentPaymentStatus', models.BooleanField(default=False)),
                ('extentCreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.orderdetails')),
            ],
        ),
    ]
