# Generated by Django 4.1.2 on 2022-10-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDR_Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('ndr_charge', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('points_earned_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('ndr_credit_card_charge', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('renter_credit_card_charge', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
            ],
        ),
    ]
