# Generated by Django 4.2.3 on 2023-07-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_portal', '0004_ndr_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDR_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
