# Generated by Django 4.2.3 on 2023-07-13 10:52

from django.db import migrations, models
import login_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_portal', '0005_ndr_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndr_documents',
            name='files',
            field=models.FileField(upload_to='documents/', validators=[login_portal.models.validate_file_extension]),
        ),
    ]
