# Generated by Django 4.2.3 on 2023-07-14 04:54

from django.db import migrations, models
import login_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_portal', '0007_alter_ndr_documents_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDR_PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='user/documents', validators=[login_portal.models.validate_file_extension])),
            ],
        ),
    ]
