# Generated by Django 4.2.3 on 2023-07-14 05:16

from django.db import migrations, models
import login_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_portal', '0008_ndr_privacypolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndr_documents',
            name='files',
            field=models.FileField(upload_to='user/PPs_documents', validators=[login_portal.models.validate_file_extension]),
        ),
    ]
