# Generated by Django 4.2.3 on 2023-07-14 05:17

from django.db import migrations, models
import login_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_portal', '0009_alter_ndr_documents_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndr_documents',
            name='files',
            field=models.FileField(upload_to='user/documents', validators=[login_portal.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='ndr_privacypolicy',
            name='files',
            field=models.FileField(upload_to='user/PP_documents', validators=[login_portal.models.validate_file_extension]),
        ),
    ]
