# Generated by Django 4.1.2 on 2022-11-09 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('otp', models.CharField(max_length=20, null=True)),
                ('otp_status', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('CountryOfBirth', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('QrCode_Account', models.FileField(blank=True, null=True, upload_to='user/qr_codes')),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('Name_First', models.CharField(max_length=100)),
                ('Name_Last', models.CharField(max_length=100)),
                ('PhotoID', models.FileField(blank=True, null=True, upload_to='user/PhotoID')),
                ('Citizenship', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('Email_Verified', models.BooleanField(default=False)),
                ('PhoneNumber_Verfied', models.BooleanField(default=False)),
                ('Email_VerificationMethod', models.CharField(max_length=50, null=True)),
                ('PhoneNumber_VerificationMethod', models.CharField(max_length=50, null=True)),
                ('Birth_Day', models.PositiveSmallIntegerField(max_length=4, null=True)),
                ('Birth_Month', models.PositiveSmallIntegerField(max_length=4, null=True)),
                ('Birth_Year', models.PositiveSmallIntegerField(max_length=6, null=True)),
                ('PhotoID_Number', models.CharField(max_length=100, null=True)),
                ('VerificationDate', models.CharField(max_length=50, null=True)),
                ('VerificationPersonalID', models.CharField(max_length=100, null=True)),
                ('CreditCard_Type', models.CharField(max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user/profile_image')),
            ],
            options={
                'db_table': 'tbl_AccountRegistration',
            },
        ),
        migrations.CreateModel(
            name='Account_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountType', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_AccountType',
            },
        ),
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_holder_name', models.CharField(max_length=200, null=True)),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('btn_number', models.CharField(max_length=15, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('branch_name', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Address_Number', models.CharField(max_length=50, null=True)),
                ('Address_Street1', models.CharField(max_length=255, null=True)),
                ('Address_Street2', models.CharField(max_length=255, null=True)),
                ('Address_City', models.CharField(max_length=50, null=True)),
                ('Address_Province', models.CharField(max_length=50, null=True)),
                ('Address_Postal', models.CharField(max_length=50, null=True)),
                ('Address_Country', models.CharField(max_length=50, null=True)),
                ('QrCode_Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_Address',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='UserAccountType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account_type'),
        ),
    ]
