# Generated by Django 4.1.2 on 2022-11-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='VerificationDate',
        ),
    ]
