# Generated by Django 4.1.2 on 2022-12-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notifications_screen_name_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referal_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
    ]
