# Generated by Django 4.1.3 on 2023-05-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_unavailabilitydate_userunavailability_unavailable_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hst_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
