# Generated by Django 4.1.3 on 2023-05-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_useravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravailability',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
