# Generated by Django 4.1.3 on 2023-05-23 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useravailability_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravailability',
            name='availabilityDate',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='XeroAccountingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('expires_in', models.CharField(blank=True, max_length=100, null=True)),
                ('token_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
