# Generated by Django 4.1.3 on 2023-05-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_xeroaccountingtoken_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bank_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='xeroaccountingtoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
