# Generated by Django 4.1.3 on 2023-06-22 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_is_bank_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeSubmitted', models.DateTimeField(auto_now_add=True, null=True)),
                ('ticketNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('issueText', models.TextField(blank=True, null=True)),
                ('dateTimeResolved', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
