# Generated by Django 4.1.3 on 2023-06-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customersupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupport',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
