# Generated by Django 4.1.3 on 2023-06-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_preferencesnotifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userunavailability',
            old_name='unavailable_from',
            new_name='unavailableDate',
        ),
        migrations.RemoveField(
            model_name='userunavailability',
            name='unavailable_to',
        ),
    ]
