# Generated by Django 4.1.3 on 2023-06-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_gpsaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Address_Lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Address_Long',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='GPSAddress',
        ),
    ]
