# Generated by Django 4.1.3 on 2023-06-27 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_address_address_lat_address_address_long_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSAddress',
            fields=[
                ('Address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Address_Number', models.CharField(max_length=50, null=True)),
                ('Address_Street1', models.CharField(max_length=255, null=True)),
                ('Address_Street2', models.CharField(max_length=255, null=True)),
                ('Address_Lat', models.CharField(max_length=255, null=True)),
                ('Address_Long', models.CharField(max_length=255, null=True)),
                ('Address_City', models.CharField(max_length=50, null=True)),
                ('Address_Province', models.CharField(max_length=50, null=True)),
                ('Address_Postal', models.CharField(max_length=50, null=True)),
                ('Address_Country', models.CharField(max_length=50, null=True)),
                ('QrCode_Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_gps_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
