# Generated by Django 4.1.3 on 2023-06-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_gpsaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsaddress',
            name='isGPS',
            field=models.BooleanField(default=False),
        ),
    ]
