# Generated by Django 4.1.3 on 2023-07-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_gpsaddress_isgps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
