# Generated by Django 4.1.3 on 2023-07-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_useravailability_availabilitydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='routing_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
