# Generated by Django 4.1.3 on 2023-07-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_userweekavailability_delete_useravailability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userweekavailability',
            old_name='endTime',
            new_name='weekAvailability',
        ),
        migrations.RemoveField(
            model_name='userweekavailability',
            name='day',
        ),
        migrations.RemoveField(
            model_name='userweekavailability',
            name='startTime',
        ),
    ]
