# Generated by Django 4.2.3 on 2023-08-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_chatabusivecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatabusivecontent',
            name='files',
            field=models.FileField(upload_to='user/abusive_document'),
        ),
    ]
