# Generated by Django 4.1.2 on 2022-12-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
