# Generated by Django 4.1.2 on 2023-01-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpickupreturn',
            options={},
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='pickup_status',
            new_name='final_pickup_status',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='return_status',
            new_name='final_return_status',
        ),
        migrations.RenameField(
            model_name='productpickupreturn',
            old_name='return_date',
            new_name='lender_pickUp_date',
        ),
        migrations.RemoveField(
            model_name='productpickupreturn',
            name='pickUp_date',
        ),
        migrations.RemoveField(
            model_name='productpickupreturn',
            name='pickup_status',
        ),
        migrations.RemoveField(
            model_name='productpickupreturn',
            name='product_img',
        ),
        migrations.RemoveField(
            model_name='productpickupreturn',
            name='return_status',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='lender_pickup_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='lender_return_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='renter_pickup_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='renter_return_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='final_pickup_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='final_return_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='lender_pickup_img',
            field=models.ImageField(blank=True, null=True, upload_to='user/lender/ProductReturnImage'),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='lender_pickup_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='lender_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='lender_return_img',
            field=models.ImageField(blank=True, null=True, upload_to='user/lender/ProductPickupImage'),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='lender_return_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='renter_pickUp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='renter_pickup_img',
            field=models.ImageField(blank=True, null=True, upload_to='user/renter/ProductPickupImage'),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='renter_pickup_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='renter_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='renter_return_img',
            field=models.ImageField(blank=True, null=True, upload_to='user/renter/ProductReturnImage'),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='renter_return_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='sales_month',
            field=models.CharField(default='January', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='sales_year',
            field=models.CharField(default='2023', max_length=100),
        ),
    ]
