# Generated by Django 4.1.2 on 2023-01-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productpickupreturn_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
