# Generated by Django 4.1.2 on 2023-01-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='update_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productpickupreturn',
            name='lender_pickUp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productpickupreturn',
            name='lender_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productpickupreturn',
            name='renter_pickUp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productpickupreturn',
            name='renter_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
