# Generated by Django 4.1.2 on 2023-04-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_orderdetails_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='sales_month',
            field=models.CharField(default='April', max_length=100),
        ),
    ]
