# Generated by Django 4.1.3 on 2023-04-27 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_orderdetails_sales_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unavailabilitydate',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_availability_date', to='products.products'),
        ),
    ]
