# Generated by Django 4.1.3 on 2023-05-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_orderdetails_sales_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinbox',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
