# Generated by Django 4.1.3 on 2023-05-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_requestinbox_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpickupreturn',
            name='renter_pickup_location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productpickupreturn',
            name='renter_return_location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
