# Generated by Django 4.1.3 on 2023-06-14 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_rename_rating_lenderreviews_lenderrating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lenderreviews',
            old_name='lenderRating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='lenderreviews',
            name='productRating',
        ),
        migrations.CreateModel(
            name='RenterReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renterRating', models.IntegerField(null=True)),
                ('about_renter', models.TextField(null=True)),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myReview', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
