# Generated by Django 4.1.3 on 2023-06-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_lenderreviews_about_renter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='reward_points',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
