# Generated by Django 4.1.3 on 2023-06-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_lenderreviews_about_renter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportincident',
            name='securityDeposit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='date_of_payment',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
