# Generated by Django 4.1.3 on 2023-06-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_reportincident_securitydeposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='date_of_payment',
            field=models.DateField(auto_now_add=True),
        ),
    ]
