# Generated by Django 4.1.3 on 2023-06-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_orderdetails_date_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
