# Generated by Django 4.1.3 on 2023-07-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_orderdetails_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='delivery_fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
