# Generated by Django 4.1.3 on 2023-07-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_orderdetails_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportincident',
            name='lateFees',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
