# Generated by Django 4.1.3 on 2023-07-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_reportincident_latefees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'ordering': ['-date_of_payment']},
        ),
        migrations.RenameField(
            model_name='reportincident',
            old_name='reported_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='reportincident',
            name='reported_on',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='date_of_payment',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
