# Generated by Django 4.2.3 on 2023-08-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_orderdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='sales_month',
            field=models.CharField(default='August', max_length=100),
        ),
    ]
